version: '3'

services:
  clickhouse_tg_bot:
    image: yandex/clickhouse-server
    restart: on-failure
    ports:
      - "8123:8123"
    volumes:
      - ./click_data:/var/lib/clickhouse
      - ./table_create:/docker-entrypoint-initdb.d
