version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - click_vol:/var/lib/clickhouse
      - ./table_create:/docker-entrypoint-initdb.d

volumes:
  click_vol:
